import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import TopNavbar from "@/app/components/navbar/top-nav/TopNav";
import { icons } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Nice soo marketplace",
  description: "Generated by create next app",
  icons: {
    icon: "/images/nice-so.jpg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative md:pt-22 pt-20 pb-20`}
      >
        <TopNavbar />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
